const read = (key, fallback) => { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) : fallback; } catch { return fallback; } };
const write = (key, value) => { try { localStorage.setItem(key, JSON.stringify(value)); return true; } catch { return false; } };
const accounts = { user1: '123456789', user2: '123456789' };
const authKey = 'fitbuddyAuthUser';
const scopedKey = key => `${key}:${getCurrentUser()?.username || 'guest'}`;
export const getCurrentUser = () => read(authKey, null);
export const login = (username, password) => { if (accounts[username] !== password) return false; return write(authKey, { username }); };
export const logout = () => { try { localStorage.removeItem(authKey); return true; } catch { return false; } };
export const savePreferences = value => write(scopedKey('userPreferences'), value);
export const getPreferences = () => read(scopedKey('userPreferences'), null);
export const saveCurrentPlan = value => write(scopedKey('currentPlan'), value);
export const getCurrentPlan = () => read(scopedKey('currentPlan'), null);
export const savePlan = value => { const plans = read(scopedKey('savedPlans'), []); return write(scopedKey('savedPlans'), [value, ...plans.filter(plan => plan.id !== value.id)]); };
export const getSavedPlans = () => read(scopedKey('savedPlans'), []);
export const getCompletedWorkouts = () => read(scopedKey('completedWorkouts'), []);
export const setWorkoutCompleted = (id, completed) => { const current = getCompletedWorkouts().filter(item => item !== id); if (completed) current.push(id); return write(scopedKey('completedWorkouts'), current); };
export const completeWorkout = id => { const completed = getCompletedWorkouts(); if (!completed.includes(id)) { completed.push(id); write(scopedKey('completedWorkouts'), completed); } return completed; };
export const calculateProgress = plan => { if (!plan?.workouts?.length) return 0; return Math.round((getCompletedWorkouts().filter(id => plan.workouts.some(workout => workout.id === id)).length / plan.workouts.length) * 100); };
export const calculateStreak = () => { const dates = read(scopedKey('workoutDates'), []); const unique = [...new Set(dates)].sort().reverse(); if (!unique.length) return 0; let streak = 0; let cursor = new Date(); cursor.setHours(0,0,0,0); for (const date of unique) { const current = new Date(date); current.setHours(0,0,0,0); const diff = Math.round((cursor - current) / 86400000); if (diff > 1) break; if (diff <= 1) { streak++; cursor = current; } } return streak; };
export const recordWorkoutDate = () => { const dates = read(scopedKey('workoutDates'), []); dates.push(new Date().toISOString().slice(0,10)); write(scopedKey('workoutDates'), dates); };
